In [1]:
import pandas as pd

In [2]:
csv_file = "Analysis/AllCountryDF.csv"
country_df = pd.read_csv(csv_file, encoding="utf-8")
country_df

,Unnamed: 0,channel_title,no_of_vids,trending_date,title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled
0,0,SET India,192,17.14.11,Crime Patrol Dial 100 - क्राइम पेट्रोल - Ep 65...,24,2017-11-12T15:34:31.000Z,210478,905,176,85,False
1,1,MSNBC,189,17.14.11,Barnicle: World Leaders Are Laughing At The US...,25,2017-11-13T14:53:22.000Z,200264,2947,317,2321,False
2,2,FBE,188,17.14.11,YOUTUBERS REACT TO TOP 10 TWITTER ACCOUNTS OF ...,24,2017-11-12T22:00:01.000Z,960747,31810,668,5335,False
3,3,The Young Turks,186,17.14.11,The Alt-Right Is Crushing On Taylor Swift,25,2017-11-13T02:00:00.000Z,100394,1619,907,1595,False
4,4,REACT,183,17.14.11,DO COLLEGE KIDS KNOW 80s MUSIC? #8 (REACT: Do ...,24,2017-11-12T20:00:01.000Z,549374,16832,248,3579,False
...,...,...,...,...,...,...,...,...,...,...,...,...
45694,45694,onsetfacilities.com,1,18.24.01,Real-time Compositing Demo / UE4 On-Set Facili...,22,2018-01-06T12:31:19.000Z,404058,2980,44,165,False
45695,45695,ladygagaarraza,1,17.20.11,Lady Gaga - The Cure (Live at AMA's from Joann...,23,2017-11-20T02:45:15.000Z,18916,1425,28,180,False
45696,45696,So I Had This Idea...,1,18.14.02,I Built The Boring Company Flamethrower!,28,2018-02-06T12:51:33.000Z,97217,1271,87,85,False
45697,45697,Caters Clips,1,17.15.11,World's First Engagement Ring Phone Case,25,2017-11-10T08:00:03.000Z,90454,211,65,59,False
45698,45698,chris lee,1,17.23.11,Highlights of the EA predatory behavior announ...,22,2017-11-21T19:29:03.000Z,160012,0,0,1722,False